AWSTemplateFormatVersion: "2010-09-09"

Description: "Organize API Gatway Private Integration"

Transform: 
  - "AWS::LanguageExtensions"

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Metadata                                                                                      ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Domain Settings
        Parameters:
          - HostedZoneId
          - Fqdn
      - Label:
          default: API Gatway Settings
        Parameters:
          - DeploymentTrigger

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Parameters                                                                                    ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Parameters: 
  HostedZoneId:
    Description: Public Hosted Zone ID
    Type: String
  Fqdn:
    Description: API Gateway Custom Domain Name
    Type: String
  DeploymentTrigger:
    Description: Change this value to force API redeployment
    Type: String
    Default: v1

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Mappings                                                                                      ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Mappings:
  VpcParams:
    System:
      Name: system-vpc
      Cidr: 192.168.0.0/16
      Tenancy: default
      DnsHost: true
      DnsSupport: true
    Bastion:
      Name: bastion-vpc
      Cidr: 192.255.0.0/16
      Tenancy: default
      DnsHost: true
      DnsSupport: true
  SubnetParams:
    SystemAlbPrivateA:
      Name: system-alb-private-a
      Az: a
      Cidr: 192.168.1.0/24
      Public: false
      VpcName: SystemVpc
    SystemAlbPrivateC:
      Name: system-alb-private-c
      Az: c
      Cidr: 192.168.2.0/24
      Public: false
      VpcName: SystemVpc
    SystemEc2PrivateA:
      Name: system-ec2-private-a
      Az: a
      Cidr: 192.168.3.0/24
      Public: false
      VpcName: SystemVpc
    BastionEc2PublicA:
      Name: bastion-ec2-public-a
      Az: a
      Cidr: 192.255.1.0/24
      Public: true
      VpcName: BastionVpc
  EipParams:
    Ec2:
      Name: ec2-eip
    NatAzA:
      Name: nat-a-eip
    NatAzC:
      Name: nat-c-eip
  CognitoParams:
    ResourceServerIdentifier:
      Name: api
    Scope:
      Read: read
      Write: write
  ApiParams:
    Stage:
      Name: prod

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Conditions                                                                                    ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
# Conditions: 

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Resources                                                                                     ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Resources:
  ############################################################
  # VPC
  ############################################################ 
  "Fn::ForEach::Vpc":
    - VpcVariable
    - - System
      - Bastion
    - ${VpcVariable}Vpc:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: !FindInMap [VpcParams, !Ref VpcVariable, Cidr]
          EnableDnsHostnames: !FindInMap [VpcParams, !Ref VpcVariable, DnsHost]
          EnableDnsSupport: !FindInMap [VpcParams, !Ref VpcVariable, DnsSupport]
          InstanceTenancy: !FindInMap [VpcParams, !Ref VpcVariable, Tenancy]
          Tags:
            - Key: Name
              Value: !FindInMap [VpcParams, !Ref VpcVariable, Name]

  ############################################################
  # Subnet
  ############################################################ 
  "Fn::ForEach::Subnet":
    - SubnetVariable
    - - SystemAlbPrivateA
      - SystemAlbPrivateC
      - SystemEc2PrivateA
      - BastionEc2PublicA
    - ${SubnetVariable}Subnet:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref
            "Fn::FindInMap": [SubnetParams, !Ref SubnetVariable, VpcName]
          CidrBlock: !FindInMap [SubnetParams, !Ref SubnetVariable, Cidr]
          AvailabilityZone: !Sub
            - "${AWS::Region}${Az}"
            - Az: !FindInMap [SubnetParams, !Ref SubnetVariable, Az]
          MapPublicIpOnLaunch: !FindInMap [SubnetParams, !Ref SubnetVariable, Public]
          Tags:
            - Key: Name
              Value: !FindInMap [SubnetParams, !Ref SubnetVariable, Name]

  ############################################################
  # Network ACL
  ############################################################ 
  NaclSystem:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref SystemVpc
      Tags:
        - Key: Name
          Value: system-nacl
  
  NaclSystemIngressAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NaclSystem
      RuleNumber: 100
      Egress: false
      Protocol: -1
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  NaclSystemEgressAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NaclSystem
      RuleNumber: 100
      Egress: true
      Protocol: -1
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  NaclBastion:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref BastionVpc
      Tags:
        - Key: Name
          Value: bastion-nacl

  NaclBastionIngressAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NaclBastion
      RuleNumber: 100
      Egress: false
      Protocol: -1
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  NaclBastionEgressAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NaclBastion
      RuleNumber: 100
      Egress: true
      Protocol: -1
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  ############################################################
  # Elastic IP
  ############################################################ 
  "Fn::ForEach::Eip":
    - EipVariable
    - - Ec2
      - NatAzA
      - NatAzC
    - ${EipVariable}Eip:
        Type: AWS::EC2::EIP
        Properties:
          Tags:
            - Key: Name
              Value: !FindInMap [EipParams, !Ref EipVariable, Name]

  ############################################################
  # Internet Gateway
  ############################################################ 

  ############################################################
  # NAT Gatway - Regional
  ############################################################ 

  ############################################################
  # Route Table
  ############################################################ 

  ############################################################
  # KeyPair
  ############################################################ 
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: bastion-keypair
      KeyType: ed25519
      KeyFormat: pem
      Tags:
        - Key: Name
          Value: bastion-keypair

  ############################################################
  # Cognito User Pool
  ############################################################
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      UserPoolName: "idp"
      ### Authentication
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      ### Settings
      UserPoolTier: "ESSENTIALS"
      UserPoolTags:
        Name: "idp"
      DeletionProtection: INACTIVE

  ############################################################
  # User Pool Domain - for Token Endpoint
  ############################################################
  Domain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: m2m-demo
      ManagedLoginVersion: 2

  ############################################################
  # Resource Server
  ############################################################
  CognitoResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref UserPool
      Name: backend-api
      Identifier: !FindInMap [CognitoParams, ResourceServerIdentifier, Name]
      Scopes:
        - ScopeName: !FindInMap [CognitoParams, Scope, Read]
          ScopeDescription: Read access
        - ScopeName: !FindInMap [CognitoParams, Scope, Write]
          ScopeDescription: Write access

  ############################################################
  # App Client - m2m
  ############################################################
  M2mClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: "m2m-app"
      UserPoolId: !Ref UserPool
      AuthSessionValidity: 3
      RefreshTokenValidity: 5
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      EnableTokenRevocation: true
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - !Sub
          - '${identify}/${scope}'
          - identify: !FindInMap [CognitoParams, ResourceServerIdentifier, Name]
            scope: !FindInMap [CognitoParams, Scope, Read]
        - !Sub
          - '${identify}/${scope}'
          - identify: !FindInMap [CognitoParams, ResourceServerIdentifier, Name]
            scope: !FindInMap [CognitoParams, Scope, Write]
      AllowedOAuthFlowsUserPoolClient: true

  ############################################################
  # API Gateway
  ############################################################
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: rest-api
      Description: Test Rest API (Any)
      EndpointConfiguration:
        IpAddressType: ipv4
        Types:
          - REGIONAL
      ApiKeySourceType: HEADER # X-API-Key
      DisableExecuteApiEndpoint: true
      Policy: !Sub
        - |
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Principal": "*",
                      "Action": "execute-api:Invoke",
                      "Resource": [
                          "execute-api:/*"
                      ],
                      "Condition": {
                          "IpAddress": {
                              "aws:SourceIp": "${sourceIp}"
                          }
                      }
                  }
              ]
          }
        - sourceIp: !Sub "${Ec2Eip}/32"
      Tags:
        - Key: Name
          Value: rest-api

  ############################################################
  # Resource - Any Path
  ############################################################
  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: "{proxy+}"

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Outputs                                                                                       ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
# Outputs: