AWSTemplateFormatVersion: "2010-09-09"

Description: "Organize API Gatway Private Integration"

Transform: 
  - "AWS::LanguageExtensions"

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Metadata                                                                                      ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Domain Settings
        Parameters:
          - HostedZoneId
          - Fqdn
      - Label:
          default: API Gatway Settings
        Parameters:
          - DeploymentTrigger
      - Label:
          default: Access Source IP CIDR List
        Parameters:
          - AccessIp

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Parameters                                                                                    ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Parameters: 
  HostedZoneId:
    Description: Public Hosted Zone ID
    Type: String
  Fqdn:
    Description: API Gateway Custom Domain Name
    Type: String
  DeploymentTrigger:
    Description: Change this value to force API redeployment
    Type: String
    Default: v1
  AccessIp:
    Description: Restrict Access IP
    Type: CommaDelimitedList

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Mappings                                                                                      ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Mappings:
  VpcParams:
    System:
      Name: system-vpc
      Cidr: 192.168.0.0/16
      Tenancy: default
      DnsHost: true
      DnsSupport: true
  SubnetParams:
    SystemAlbPrivateA:
      Name: system-alb-private-a
      Az: a
      Cidr: 192.168.1.0/24
      Public: false
      VpcName: SystemVpc
    SystemAlbPrivateC:
      Name: system-alb-private-c
      Az: c
      Cidr: 192.168.2.0/24
      Public: false
      VpcName: SystemVpc
    SystemEc2PrivateA:
      Name: system-ec2-private-a
      Az: a
      Cidr: 192.168.3.0/24
      Public: false
      VpcName: SystemVpc
  EipParams:
    NatAzA:
      Name: nat-a-eip
    NatAzC:
      Name: nat-c-eip
  SgParams:
    Alb:
      Name: alb-sg
      Description: For ALB SG
    Ec2:
      Name: ec2-sg
      Description: For EC2 SG
    VpcLink:
      Name: vpc-link-sg
      Description: For VPC Link SG
  CognitoParams:
    ResourceServerIdentifier:
      Name: api
    Scope:
      Read: read
      Write: write
  ApiParams:
    Stage:
      Name: prod

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Conditions                                                                                    ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
# Conditions: 

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Resources                                                                                     ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
Resources:
  ############################################################
  # VPC
  ############################################################ 
  "Fn::ForEach::Vpc":
    - VpcVariable
    - - System
    - ${VpcVariable}Vpc:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: !FindInMap [VpcParams, !Ref VpcVariable, Cidr]
          EnableDnsHostnames: !FindInMap [VpcParams, !Ref VpcVariable, DnsHost]
          EnableDnsSupport: !FindInMap [VpcParams, !Ref VpcVariable, DnsSupport]
          InstanceTenancy: !FindInMap [VpcParams, !Ref VpcVariable, Tenancy]
          Tags:
            - Key: Name
              Value: !FindInMap [VpcParams, !Ref VpcVariable, Name]

  ############################################################
  # Subnet
  ############################################################ 
  "Fn::ForEach::Subnet":
    - SubnetVariable
    - - SystemAlbPrivateA
      - SystemAlbPrivateC
      - SystemEc2PrivateA
    - ${SubnetVariable}Subnet:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref
            "Fn::FindInMap": [SubnetParams, !Ref SubnetVariable, VpcName]
          CidrBlock: !FindInMap [SubnetParams, !Ref SubnetVariable, Cidr]
          AvailabilityZone: !Sub
            - "${AWS::Region}${Az}"
            - Az: !FindInMap [SubnetParams, !Ref SubnetVariable, Az]
          MapPublicIpOnLaunch: !FindInMap [SubnetParams, !Ref SubnetVariable, Public]
          Tags:
            - Key: Name
              Value: !FindInMap [SubnetParams, !Ref SubnetVariable, Name]

  ############################################################
  # Network ACL
  ############################################################ 
  NaclSystem:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref SystemVpc
      Tags:
        - Key: Name
          Value: system-nacl
  
  NaclSystemIngressAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NaclSystem
      RuleNumber: 100
      Egress: false
      Protocol: -1
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  NaclSystemEgressAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NaclSystem
      RuleNumber: 100
      Egress: true
      Protocol: -1
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  "Fn::ForEach::NaclAssoc":
    - AssocVariable
    - - SystemAlbPrivateASubnet
      - SystemAlbPrivateCSubnet
      - SystemEc2PrivateASubnet
    - ${AssocVariable}NaclAssoc:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
          NetworkAclId: !Ref NaclSystem
          SubnetId: !GetAtt
            - !Ref AssocVariable
            - SubnetId

  ############################################################
  # Elastic IP
  ############################################################ 
  "Fn::ForEach::Eip":
    - EipVariable
    - - NatAzA
      - NatAzC
    - ${EipVariable}Eip:
        Type: AWS::EC2::EIP
        Properties:
          Tags:
            - Key: Name
              Value: !FindInMap [EipParams, !Ref EipVariable, Name]

  ############################################################
  # Internet Gateway
  ############################################################
  Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: igw

  IgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref Igw
      VpcId: !Ref SystemVpc

  ############################################################
  # NAT Gatway - Regional
  ############################################################
  # Internet Gateway が対象VPCにアタッチされていること
  RegionalNat:
    Type: AWS::EC2::NatGateway
    DependsOn:
      - IgwAttach
    Properties:
      VpcId: !Ref SystemVpc
      AvailabilityMode: regional
      ConnectivityType: public
      MaxDrainDurationSeconds: 60
      AvailabilityZoneAddresses:
        - AvailabilityZone: !Sub "${AWS::Region}a"
          AllocationIds:
            - !GetAtt NatAzAEip.AllocationId
        - AvailabilityZone: !Sub "${AWS::Region}c"
          AllocationIds:
            - !GetAtt NatAzCEip.AllocationId
      Tags:
        - Key: Name
          Value: regional-nat
      
  ############################################################
  # Route Table
  ############################################################ 
  SystemAlbSubnetRtb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SystemVpc
      Tags:
        - Key: Name
          Value: alb-subnet-rtb

  AlbRtbAssocPrivateA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SystemAlbSubnetRtb
      SubnetId: !Ref SystemAlbPrivateASubnet

  AlbRtbAssocPrivateC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SystemAlbSubnetRtb
      SubnetId: !Ref SystemAlbPrivateCSubnet  

  SystemEc2SubnetRtb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SystemVpc
      Tags:
        - Key: Name
          Value: ec2-subnet-rtb
  
  SystemEc2SubnetRtbRouteNgw:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref SystemEc2SubnetRtb
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref RegionalNat

  Ec2RtbAssocPrivateA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SystemEc2SubnetRtb
      SubnetId: !Ref SystemEc2PrivateASubnet

  ############################################################
  # KeyPair
  ############################################################ 
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: bastion-keypair
      KeyType: ed25519
      KeyFormat: pem
      Tags:
        - Key: Name
          Value: bastion-keypair

  ############################################################
  # Security Group
  ############################################################ 
  "Fn::ForEach::SecurityGroup":
    - SgVariable
    - - Alb
      - Ec2
      - VpcLink
    - ${SgVariable}Sg:
        Type: AWS::EC2::SecurityGroup
        Properties:
          VpcId: !Ref SystemVpc
          GroupName: !FindInMap [SgParams, !Ref SgVariable, Name]
          GroupDescription: !FindInMap [SgParams, !Ref SgVariable, Description]
          Tags:
            - Key: Name
              Value: !FindInMap [SgParams, !Ref SgVariable, Name]

  "Fn::ForEach::SgEgressAllAllow":
    - SgVariable
    - - AlbSg
      - Ec2Sg
      - VpcLinkSg
    - ${SgVariable}EgressAllAllow:
        Type: AWS::EC2::SecurityGroupEgress
        Properties:
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
          Description: "Unrestricted"
          GroupId: !GetAtt 
            - !Ref SgVariable
            - GroupId

  AlbSgIngressHttp:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: "tcp"
      SourceSecurityGroupId: !Ref VpcLinkSg
      FromPort: 80
      ToPort: 80
      Description: "Allow HTTP From VPC Link SG"
      GroupId: !Ref AlbSg

  Ec2SgIngressHttp:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: "tcp"
      SourceSecurityGroupId: !Ref AlbSg
      FromPort: 80
      ToPort: 80
      Description: "Allow HTTP From ALB SG"
      GroupId: !Ref Ec2Sg

  ############################################################
  # Cognito User Pool
  ############################################################
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      UserPoolName: "idp"
      ### Authentication
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      ### Settings
      UserPoolTier: "ESSENTIALS"
      UserPoolTags:
        Name: "idp"
      DeletionProtection: INACTIVE

  ############################################################
  # User Pool Domain - for Token Endpoint
  ############################################################
  Domain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: m2m-demo
      ManagedLoginVersion: 2

  ############################################################
  # Resource Server
  ############################################################
  CognitoResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref UserPool
      Name: backend-api
      Identifier: !FindInMap [CognitoParams, ResourceServerIdentifier, Name]
      Scopes:
        - ScopeName: !FindInMap [CognitoParams, Scope, Read]
          ScopeDescription: Read access
        - ScopeName: !FindInMap [CognitoParams, Scope, Write]
          ScopeDescription: Write access

  ############################################################
  # App Client - m2m
  ############################################################
  M2mClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - Domain
      - CognitoResourceServer
    Properties:
      ClientName: "m2m-app"
      UserPoolId: !Ref UserPool
      AuthSessionValidity: 3
      RefreshTokenValidity: 5
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      EnableTokenRevocation: true
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - !Sub
          - '${identify}/${scope}'
          - identify: !FindInMap [CognitoParams, ResourceServerIdentifier, Name]
            scope: !FindInMap [CognitoParams, Scope, Read]
        - !Sub
          - '${identify}/${scope}'
          - identify: !FindInMap [CognitoParams, ResourceServerIdentifier, Name]
            scope: !FindInMap [CognitoParams, Scope, Write]
      AllowedOAuthFlowsUserPoolClient: true

  ############################################################
  # EC2
  ############################################################

  ############################################################
  # ALB
  ############################################################

  ############################################################
  # TargetGroup
  ############################################################

  ############################################################
  # Listener
  ############################################################

  ############################################################
  # Listener Rule
  ############################################################

  ############################################################
  # VPC Link V2
  ############################################################
  VpcLinkV2:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: vpc-link-v2
      SubnetIds:
        - !Ref SystemAlbPrivateASubnet
        - !Ref SystemAlbPrivateCSubnet
      SecurityGroupIds:
        - !Ref VpcLinkSg
      Tags:
        Name: vpc-link-v2

  ############################################################
  # API Gateway
  ############################################################
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: rest-api
      Description: Test Rest API (Any)
      EndpointConfiguration:
        IpAddressType: ipv4
        Types:
          - REGIONAL
      SecurityPolicy: SecurityPolicy_TLS13_1_3_2025_09
      EndpointAccessMode: STRICT # or BASIC
      ApiKeySourceType: HEADER # X-API-Key
      DisableExecuteApiEndpoint: true
      Policy:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": "*",
              "Action": "execute-api:Invoke",
              "Resource": ["execute-api:/*"],
              "Condition": {
                "IpAddress": {
                  "aws:SourceIp": !Ref AccessIp
                }
              }
            }
          ]
        }
      Tags:
        - Key: Name
          Value: rest-api

  ############################################################
  # Resource - Any Path
  ############################################################
  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: "{proxy+}"

  ############################################################
  # Method - VPC Link
  ############################################################

  ############################################################
  # Deployment
  ############################################################

  ############################################################
  # ACM
  ############################################################
  
  ############################################################
  # Custom Domain
  ############################################################

  ############################################################
  # Record
  ############################################################

# ╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ Outputs                                                                                       ║
# ╠═════════════════════╤═════════════════════════════════════════════════════════════════════════╣
# ╚═════════════════════╧═════════════════════════════════════════════════════════════════════════╝
# Outputs: